FROM node:23.8.0-slim AS base

RUN corepack enable
RUN apt update && apt install -y curl python3 make g++ build-essential

FROM base AS build

COPY ./KRO-website /app
WORKDIR /app

RUN pnpm install --frozen-lockfile
RUN pnpm build

FROM node:23.8.0-slim
COPY --from=build /app/.output /app

EXPOSE 3000

ENV TZ=Europe/Berlin

CMD [ "node", ".output/server/index.mjs" ]